

set(libphys_SOURCES
	sources/Actors/Actor.cpp
sources/Actors/Actor.h
sources/Actors/DynamicActor.cpp
sources/Actors/DynamicActor.h
sources/Actors/RigidType.h
sources/Actors/StaticActor.cpp
sources/Actors/StaticActor.h
sources/ConfigPhysixTolerance.h
sources/Controller.h
sources/ControllerBehaviorCallback.cpp
sources/ControllerBehaviorCallback.h
sources/Debug/Debug.cpp
sources/Debug/Debug.h
sources/DefaultColliders/Primitives/BoxCollider.cpp
sources/DefaultColliders/Primitives/BoxCollider.h
sources/DefaultColliders/Primitives/CapsuleCollider.cpp
sources/DefaultColliders/Primitives/CapsuleCollider.h
sources/DefaultColliders/Primitives/Collision.cpp
sources/DefaultColliders/Primitives/Collision.h
sources/DefaultColliders/Primitives/PlaneCollider.cpp
sources/DefaultColliders/Primitives/PlaneCollider.h
sources/DefaultColliders/Primitives/SphereCollider.cpp
sources/DefaultColliders/Primitives/SphereCollider.h
sources/Forces/ForceMode.h
sources/Header.h
sources/Joint/JointBase.cpp
sources/Joint/JointBase.h
sources/PhysicsMaterial/Material.cpp
sources/PhysicsMaterial/Material.h
sources/PhysixCollider.cpp
sources/PhysixCollider.h
sources/PhysixManager.cpp
sources/PhysixManager.h
sources/PTransform.cpp
sources/PTransform.h
sources/Raycast/Raycast.cpp
sources/Raycast/Raycast.h
sources/RigidBody.cpp
sources/RigidBody.h
sources/Shapes/ComplexMesh/ConvexMesh.cpp
sources/Shapes/ComplexMesh/ConvexMesh.h
sources/Shapes/ComplexMesh/ConvexMeshDescriptor.cpp
sources/Shapes/ComplexMesh/ConvexMeshDescriptor.h
sources/Shapes/ComplexMesh/TriangleMesh.cpp
sources/Shapes/ComplexMesh/TriangleMesh.h
sources/Shapes/ComplexMesh/TriangleMeshDescriptor.cpp
sources/Shapes/ComplexMesh/TriangleMeshDescriptor.h
sources/Shapes/Primitives/BoxShape.cpp
sources/Shapes/Primitives/BoxShape.h
sources/Shapes/Primitives/CapsuleShape.cpp
sources/Shapes/Primitives/CapsuleShape.h
sources/Shapes/Primitives/PlaneShape.h
sources/Shapes/Primitives/SphereShape.cpp
sources/Shapes/Primitives/SphereShape.h
sources/Shapes/Shape.h
sources/SimulationEventCallback.cpp
sources/SimulationEventCallback.h
sources/Test2.cpp
sources/Test2.h
sources/UserControllerHitReport.cpp
sources/UserControllerHitReport.h
	)
